name: Publish

on:
  - push

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 7546e0e8b2da3fd06fff1373debbce8f
          projectName: bithesis-wiki
          directory: wiki/.vitepress/dist
          # Enable this to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
